string $mgl_root = `pwd`;
python("import os,sys;");
python("os.chdir('" +$mgl_root+ "');os.chdir('../');MGL_ROOT = os.path.abspath(os.curdir);");
python("sys.path.append(MGL_ROOT)");
python("os.chdir('../');MGL_ROOT = os.path.abspath(os.curdir);");
python("from ePMV import installer;inst = installer.Installer(mgl=MGL_ROOT);");
python("gui = installer.InstGui(inst=inst,mgl=MGL_ROOT)");
python("gui.display()");